WIP 検索履歴の追加
traPtitech/traQ_S-UI pull request #2202
Opened 2021-05-19 13:18 UTC by Ras96

履歴が表示されるところまでは作りましたが、履歴が更新されません。

2021-05-22 13:10 UTC, sapphi-red commented on src/components/Main/CommandPalette/SearchSuggestion.vue
> +    <search-suggestion-history-item
`<search-suggestion-query-item>`使っていい気がします

2021-05-22 13:10 UTC, sapphi-red commented on src/components/Main/CommandPalette/SearchSuggestion.vue
> +    ) //FIXME readonlyのままでOK?
(Writeable Computedでない)computedな値は書き換えられないのでreadonlyであるべきなので問題ないです 👍

2021-05-22 13:10 UTC, sapphi-red commented on src/store/app/getters.ts
> +    return state.searchHistories
`state`を返すだけなら`getter`を介さずに`store.state.app.searchHistories`でアクセスできるのでそれで問題ないです

それとこれはgettersを書かないなら関係ないんですが、`getSearchHistories`という名前は重言みたいな感じになるので(gettersの中にある地点で取得するのは当然なので)`searchHistories`とかでよさそうです

2021-05-22 13:10 UTC, sapphi-red commented on src/store/app/state.ts
> +  /** 検索履歴 */
新しい順であることを明記しておいたほうがよさそうです

2021-05-22 13:10 UTC, sapphi-red commented on src/store/app/mutations.ts
> +    if (index !== -1) state.searchHistories.splice(index, 1)
```suggestion
    if (index !== -1) {
      state.searchHistories.splice(index, 1)
    }

```
こうしてほしいです :pray: 

- 早期リターン以外の条件分岐は見やすさのためにブロックにしたいです
- この`splice`と`indexOf`は存在してたら消すという意味の二行なので、下とは区切りをつけるために空行を挟みたいです

2021-05-22 13:10 UTC, sapphi-red commented on src/store/app/mutations.ts
> +    state.searchHistories = state.searchHistories.slice(0, 5)
ここまで全部破壊的に操作するならここも破壊的に`if (state.searchHistories.length > 5) state.searchHistories.pop()`にしたほうがよさそうです

2021-05-26 07:51 UTC, sapphi-red commented on src/components/Main/CommandPalette/SearchSuggestionHistoryItem.vue
> +      @click.stop="removeHistorySuggestion(label)"
ここで消すのではなくて、親にremoveイベント送って親で消してほしいです :pray:
これは選択のほうもそういう実装になってるので一貫性を保ちたいからです

2021-05-26 07:51 UTC, sapphi-red commented on src/components/Main/CommandPalette/SearchSuggestionHistoryItem.vue
> +  grid-template-columns: 1fr 2.5rem;
```suggestion
  padding: 0.5rem 1rem 0.5rem 2rem;
  display: grid;
  grid-template-columns: 1fr min-content;
```
意図しているのはこうだったりしませんか？ (右側に余白を入れたいのであってアイコンのとこの幅を変えたいわけではない)

2021-05-26 07:51 UTC, sapphi-red commented on src/components/Main/CommandPalette/SearchSuggestionHistoryItem.vue
> +    select: (label: string) => true //TODO 必要？
```suggestion
    select: (label: string) => true
```
補完とかの都合上、明示するほうがいいです 🤘

2021-05-26 07:51 UTC, sapphi-red commented on src/components/Main/CommandPalette/SearchSuggestionHistoryItem.vue
> +.icon {
```suggestion
.icon {
  margin-left: 0.5rem;
```
履歴に長い文字列があったときに、横に余白がほしいです 🖖

2021-05-26 07:51 UTC, sapphi-red commented on src/providers/commandPalette.ts
> +    if (commandPaletteStore.currentInput) {
```suggestion
    if (commandPaletteStore.currentInput !== '') {
```
空文字列でないときということを明示しておきたいです

2021-05-26 07:51 UTC, sapphi-red commented on src/store/app/state.ts
> +  searchHistories: string[] //TODO 型
```suggestion
  messageSearchHistories: string[]
```
検索はメッセージ検索以外にも存在するので(ほとんどはfilterって言い方にはなっていますが)一応`message`をつけておきたいです :pray:
あと型はこれで問題ないです

2021-05-26 07:51 UTC, sapphi-red commented on src/store/app/mutations.ts
> +    // return state.searchHistories.filter(history => history !== oldHistory)
```suggestion
```
消し忘れ

2021-05-26 07:51 UTC, sapphi-red commented on src/store/app/index.ts
> +  path: ['app.searchHistories'], //TODO 名前
```suggestion
  path: ['app.messageSearchHistories'],
```
前述

2021-05-27 11:29 UTC, Ras96 commented
修正しました
一部変数名も変更しましたがおかしかったら教えて頂けるとありがたいです:pray:

2021-05-27 16:17 UTC, sapphi-red requested changes
デグレってます
ほかはよさそうです 👍

2021-05-27 16:17 UTC, sapphi-red commented on src/components/Main/CommandPalette/SearchSuggestionHistoryItem.vue
> +      @click="onClose"
```suggestion
      @click.stop="onClose"
```
ここ消えてます

2021-05-27 23:28 UTC, Ras96 commented
直しました:pray:

2021-05-28 00:36 UTC, sapphi-red commented on src/components/Main/CommandPalette/SearchSuggestionHistoryItem.vue
> +      :inner-size="12"
```suggestion
```

2021-05-28 00:45 UTC, sapphi-red approved these changes
:yosa: :tada:

2021-05-28 00:46 UTC, merged