閲覧中ユーザーの+nをクリックしてサイドバーの閲覧者を表示するように
traPtitech/traQ_S-UI pull request #3357
Opened 2022-05-14 06:53 UTC by zer0-star

resolve #1082

クリックできることが分かりづらいかも

2022-05-14 07:28 UTC, zer0-star commented
副作用として、DMで閲覧者の詳細表示ができなくなってしまった(やろうと思えばできるけど、必要性があるのかどうか)

2022-05-14 08:23 UTC, sapphi-red requested changes
挙動はよさそうです :pro:
コードの書き方とかだけ :pray:

2022-05-14 08:23 UTC, sapphi-red commented on src/components/Main/MainView/ChannelView/ChannelSidebar/ChannelSidebarHidden.vue
> +      "
これでも動くことには動くんですが、クリックに対する処理の優先度によって動いてて、ややわかりにくいので、`user-icon-ellipsis-list`から`+n`をクリックしたイベントを送出するようにしてほしいです :pray:
`cursor: pointer`以外にも押せるときはホバー時に文字をちょっと大きくしたりするとよいかもしれないです
イベントを受け取るかは`user-icon-ellipsis-list`からはわからないので、イベントを発火するかどうかのpropも追加するとよさそうだと思います

2022-05-14 08:23 UTC, sapphi-red commented on src/components/Main/MainView/ChannelView/ChannelSidebar/ChannelSidebar.vue
> +            v-model="isViewersDetailOpen"
```suggestion
            v-model:isViewersDetailOpen="isViewersDetailOpen"
```
このコンポーネントのメインの機能ではないので、名前つきのものにしたほうがわかりやすそうです 🖖 
https://vuejs.org/guide/components/events.html#multiple-v-model-bindings

2022-05-14 08:23 UTC, sapphi-red commented on src/components/Main/MainView/ChannelView/ChannelSidebar/ChannelSidebarViewers.vue
`useVModelValueSyncer`と`useToggle`を組み合わせるときれいにかけます 🙋‍♂️ 
`useToggle`の引数に`ref`が渡せるのでそれを利用する感じです

2022-05-14 08:23 UTC, sapphi-red commented on src/components/Main/MainView/ChannelView/ChannelSidebar/ChannelSidebarViewers.vue
> +    modelValue?: boolean
ここに`?`をつけるのではなくて、`DMSidebarContent.vue`でも`v-model`に`ref`を渡すようにしてほしいです :pray:
`+n`のところで押せるようにする必要はないです 👌

2022-05-15 05:22 UTC, sapphi-red requested changes
挙動はよさそうです 👍

2022-05-15 05:22 UTC, sapphi-red commented on src/components/Main/MainView/ChannelView/ChannelSidebar/ChannelSidebarHidden.vue
> +      "
閲覧者の部分を開くためにはサイドバーを開く必要があることは、このコンポーネントでは知り得なくて、親コンポーネントで行うほうがよいので、ここでは`emit('openViewers')`だけにするのがよさそうです 🖖

2022-05-15 05:22 UTC, sapphi-red commented on src/components/Main/MainView/ChannelView/ChannelSidebar/ChannelSidebarHidden.vue
> +  cursor: pointer;
```suggestion
```

2022-05-15 05:22 UTC, sapphi-red commented on src/components/Main/MainView/ChannelView/ChannelSidebar/ChannelSidebarViewers.vue
> +onUnmounted(() => emit('update:modelValue', false))
```suggestion
const { value: isDetailOpen, toggle, close } = useToggle(
  useModelValueSyncer(props, emit)
)

onUnmounted(() => close())
```
こうするとよさそうです

2022-05-15 05:22 UTC, sapphi-red commented on src/components/UI/UserIconEllipsisList.vue
> +    clickable?: boolean
`clickable`だと曖昧なので、`countClickable`とかにするほうがよさそうです :eyes:

2022-05-15 08:56 UTC, sapphi-red approved these changes
かなり:yosa:です！ :tada: 🎊

2022-05-15 08:56 UTC, merged