タブが選択されていないときとかに閲覧状態をnoneにする
traPtitech/traQ_S-UI pull request #3740
Opened 2023-01-14 15:01 UTC by mehm8128

close https://github.com/traPtitech/traQ_S-UI/issues/861

2023-01-30 11:27 UTC, mehm8128 commented
これブラウザのウィンドウとVSCodeをどっちも最大化してあって、ウィンドウを最小化せずに切り替えるとnoneにならないから微妙かも
かといってonfocusとonblur使うと半分半分で見てるときとか余計にnoneになっちゃうときが生じちゃうからどうするのがいいんだろ

2023-03-14 16:35 UTC, ras0q requested changes
@mehm8128 具体的な解決策を提示できなくて申し訳ないんですが一部レビューしました:pray:

2023-03-14 16:35 UTC, ras0q commented on src/components/Main/MainView/ChannelView/ChannelViewContent/composables/useChannelMessageFetcher.ts
> +  }
visibleになった時に`onReachedLatest`で未読全消化させると↓のようになってしまうので対策が必要そうです 🤔 
(visibleになるのと最新メッセージまで到達するのは異なるはず)

https://user-images.githubusercontent.com/66677201/225073850-957898f9-4db7-4388-8a5c-93171f7cc996.mp4

2023-03-16 13:05 UTC, mehm8128 commented on src/components/Main/MainView/ChannelView/ChannelViewContent/composables/useChannelMessageFetcher.ts
> +  }
直してみたのですが、最新メッセージ見てる状態で別タブ開いて戻ってきたときに新しいメッセージが来てたときに、未読のまま(今commitしてある状態)になるのか未読消化しちゃっていいのかで悩んでます

2023-03-26 10:01 UTC, ras0q commented on src/components/Main/MainView/ChannelView/ChannelViewContent/composables/useChannelMessageFetcher.ts
> +  }
直感的には未読のままでいい気がします🤔

2023-03-26 10:05 UTC, mehm8128 commented on src/components/Main/MainView/ChannelView/ChannelViewContent/composables/useChannelMessageFetcher.ts
> +  }
分かりました👍

2023-03-26 10:33 UTC, ras0q approved these changes
遅れてすみません:pray:
良さそうです:+1:

2023-03-26 11:25 UTC, merged