表の中身の大きさが変化する時がたつく問題を修正
traPtitech/traQ_S-UI pull request #4030
Opened 2023-08-02 14:46 UTC by nokhnaton

こんなかんじのやつ
![image](https://github.com/traPtitech/traQ_S-UI/assets/104210327/cfced902-6d64-448f-83e9-f8b28f17c987)

2023-08-02 15:23 UTC, ras0q approved these changes
動作確認しました、よさそうです:+1:
ただ直接markdown-it編集する方がいいかもしれない
https://github.com/traPtitech/traq-markdown-it/blob/master/src/css/markdown.scss

2023-08-12 07:46 UTC, mehm8128 commented
前に発生していた記憶はちょっとあるのですが、今確認してみると元の問題が再現できてなくて確認できてないです:thonk_sweat:
他に確認できる人いればお願いします

2023-09-14 14:36 UTC, ras0q requested changes
やっぱりmarkdown-itの方修正してほしいのでrequest changesにしときます

2023-10-31 02:09 UTC, mehm8128 commented
@nokhnaton 
これmarkdown-itの方でやってもらうのでよさそうであればcloseしておいてほしいです:pray:

2024-10-22 04:58 UTC, closed without merging