オンライン表示を見やすくなったデザインに変更
traPtitech/traQ_S-UI pull request #4038
Opened 2023-08-12 07:08 UTC by mehm8128

close https://github.com/traPtitech/traQ_S-UI/issues/3751

デザインに沿って修正しました
ユーザーモーダルで縦のスペースがちょっと広い気もする

- ユーザーモーダル(PC, sp)
- ナビゲーションバーのユーザー一覧
- メッセージ入力欄のメンション時の補完ドロップダウン

の3箇所で使われているので表示の確認をお願いします

また、ユーザーモーダルではwithTooltipのコンポーネントが使われていましたが、最終オンライン日時がちょっと下見ればあるので不要だと思ったので消しました

2023-08-16 12:02 UTC, ras0q commented
モバイルだと割と短いidでもホームチャンネルが設定されているとガタつくのが気になりました👀
https://github.com/traPtitech/traQ_S-UI/assets/66677201/19e47e5c-ad69-4f1d-ae67-64501860e3a6

2023-08-16 13:09 UTC, mehm8128 commented
userの情報は最初に取得してあったusersから取ってきている(https://github.com/traPtitech/traQ_S-UI/blob/82de63ba977ac065312f34c7a4d0f05ce22feedd/src/components/Modal/UserModal/UserModal.vue#L71)のに対して、ホ－ムチャンネルの情報(detail)はモ－ダルを開いたタイミングでサ－バ－から取得している(https://github.com/traPtitech/traQ_S-UI/blob/82de63ba977ac065312f34c7a4d0f05ce22feedd/src/components/Modal/UserModal/UserModal.vue#L73)ので、どうしても表示タイミングがずれてしまうと思います
detailを取得完了するまでfeatureContainerの中身を表示しなければ(高さとかは確保していい感じの表示にする)直りそうですが、それよりは今のままの方がいい気がします:thinking:

2023-08-18 13:04 UTC, mehm8128 commented
↑に変えました

2023-09-14 14:23 UTC, ras0q requested changes
横幅が十分にあるときにホームチャンネルがなくてもボタンが表示されたままになってます:confused:
![image](https://github.com/traPtitech/traQ_S-UI/assets/66677201/0fc043a5-ef5a-4a37-baed-95c02ef68dcf)

2023-09-14 14:26 UTC, ras0q commented on src/components/Modal/UserModal/FeatureContainer/LinkButtons.vue
> +    homeChannelId?: string | null
で十分:kamo:
```suggestion
    homeChannelId: string | null
```

2023-09-14 14:33 UTC, ras0q commented on src/components/UI/OnlineIndicator.vue
>      :border-width="borderWidth"
ベストプラクティス分からないんですがindicator-dotを1つにまとめてspanを条件分けするのだと微妙ですかね？

2023-09-14 14:41 UTC, mehm8128 commented on src/components/Modal/UserModal/FeatureContainer/LinkButtons.vue
> +    homeChannelId?: string | null
このコンポーネント使ってるコンポーネントで、`detail: UserDetail`をまだサーバーから取得できていないときにundefinedになる可能性があるので外せなさそうですねー

2023-09-14 14:41 UTC, mehm8128 commented
バグについては、Mobileのコンポーネントだけ直してDesktopのコンポーネント直し忘れてたので、直しました

2023-09-14 14:42 UTC, ras0q approved these changes
よさそうです:+1:

2023-09-23 08:38 UTC, ras0q approved these changes

2023-10-15 13:30 UTC, merged