dropDownをiOSでも表示させるように
traPtitech/traQ_S-UI pull request #4114
Opened 2023-10-23 04:54 UTC by nokhnaton

動いて欲しいので、とりあえずビルドしてみて確かめる

2023-10-23 06:42 UTC, ras0q approved these changes
`window.visualViewport.offsetTop`初耳だった
Safari、PWAで確認しました
![image](https://github.com/traPtitech/traQ_S-UI/assets/66677201/b9cc9771-4fa5-4f04-8f59-cea2b1258202)![image](https://github.com/traPtitech/traQ_S-UI/assets/66677201/dc6e09ca-7211-4eda-8d81-5bc7c860cee0)

2023-11-08 01:40 UTC, mehm8128 requested changes
僕のスマホ(Android)で表示されなくなってそうです:thinking:
調査はあとでします

2023-11-09 05:34 UTC, nokhnaton commented
> 僕のスマホ(Android)で表示されなくなってそうです🤔 調査はあとでします

理由として`window.visualViewport.offsetTop`の値が正か負の:wa_deka:に設定されているくらいしか理由がパッと思いつきませんが、android持ってないので試せないです。
正直、iOSでだけ新しい式になるように書き換えるとかでもいい気はしているので、ちょっと調べてわからなさそうならiOSでだけ書き換えるようにします

2024-10-23 04:25 UTC, Pugma approved these changes
僕の Android スマホ上で動作しました〜
確認済みなので ok です

2024-10-23 04:26 UTC, merged