ファイルモーダル開いてるときにescキーを押したら閉じられるように
traPtitech/traQ_S-UI pull request #4121
Opened 2023-11-01 05:49 UTC by mehm8128

https://github.com/traPtitech/traQ_S-UI/issues/745

2023-11-13 09:07 UTC, ras0q requested changes
コードの修正案を書きました
これってどこのモーダルを指してますか？

2023-11-13 09:07 UTC, ras0q commented
optionalなのにchange requestedしちゃた

2023-11-13 10:12 UTC, mehm8128 commented on src/store/ui/modal.ts
> +  window.addEventListener('keydown', onKeyDown)
確かにそうですね、直します

2023-11-13 10:15 UTC, mehm8128 commented
影響あるのはここにあるモーダル全部だと思ってます
https://github.com/traPtitech/traQ_S-UI/blob/e4a04d44bd557782a7863d65d2835b61edd29931/src/store/ui/modal/states.ts#L11-L26

2023-11-13 10:32 UTC, SSlime-s commented
通知メンバーいじるところの入力欄とかの一部モーダルで、Esc で Clear する挙動になっているので、そこと競合してそうです (競合というか Clear を期待して Esc を押すと入力が消えて萎える)
すべて試してはないけど `FilterInput` を使っている部分 少なくともメンバー選ぶ系 (グループ周りとか) は同じようになってそうです
1. esc 入力時に Clear している部分調査してそこに `.stop` (`stopPropagation`)つける
2. modal 側で esc 時に activeElement が input じゃないときにのみ動作するようにする (こっちだと Clear するわけではない input でも閉じなくなる)

のどっちかをするとよさそう

2023-11-13 11:50 UTC, mehm8128 commented
ありがとうございます！見落としてました
対処法としては前者にしようと思うのですが、
- 1文字以上入れてるときだけstopして0文字のときはモーダル閉じるようにする
- 文字数関係なくフォーカス時にescを押したときはクエリのリセットだけされるようにする

どちらがいいと思いますか？

2023-11-13 11:55 UTC, SSlime-s commented
特に強い主張はないんですが、難しいことを言うと
- 通知モーダル -> 検索してトグルするだけだから、空なら閉じてほしい
- グループ系モーダル -> 検索して選択してまとめて追加するので、空でも閉じないでほしい

って感じです
個人的にはどうせ前者もキーボード操作だけで完結させられないので、空でも閉じなくていいんじゃないかと思います

2023-11-13 11:59 UTC, mehm8128 commented
なるほどです、確かにそうかもです

じゃあ統一して空でも閉じない方針にします:+1:

2024-01-06 08:52 UTC, ras0q approved these changes
動作確認しました
コードもいいと思います

2024-01-06 08:53 UTC, merged