メニューを開くボタンをトグルにする
traPtitech/traQ_S-UI pull request #4137
Opened 2023-11-02 09:56 UTC by saitenntaisei

#3773

2023-11-02 10:26 UTC, saitenntaisei commented
3番目を直したら4番目が壊れた
4番目を直したら3番目が壊れた

2023-11-03 08:52 UTC, mehm8128 commented
stopPropagationしたらaタグで遷移しちゃうって話だったから、`router-link`じゃなくてチャンネルリストでのチャンネル遷移みたいに↓のようにすれば一応動くようにはなりそう
https://github.com/traPtitech/traQ_S-UI/blob/6b1ea3fb511d1c8df98810572d523423cc68a6ac/src/components/Main/NavigationBar/ChannelList/ChannelElement.vue#L97-L101

ただ、a11y的にはあんまりよくないので、できれば別の方法を考えたい

2023-11-03 09:00 UTC, mehm8128 commented
大変そうなら一旦9点リーダーボタンとチャンネルのコンテキストメニューだけでPR作っちゃってもOKです！

2023-12-06 07:41 UTC, saitenntaisei commented
できたはず　acctiveelementが何かわからなかったそこのテストができてない

2023-12-06 07:42 UTC, saitenntaisei commented
@mehm8128  rereqができなかったからmention:gomen:

2023-12-26 12:03 UTC, mehm8128 reviewed
だいぶ前で忘れちゃったんですけど、今の状態ってどこもtoggleできない(開いてる状態でクリックしても閉じてくれない)気がするんですけど僕の環境だけですか？

2023-12-26 12:03 UTC, mehm8128 commented on src/components/UI/MessagePanel/MessagePanel.vue
![should](https://img.shields.io/badge/review-should-important.svg)
ヘッダーはクリックしても遷移しなくなったので、`container`のCSSから`cursor: pointer;`を外してほしいです:pray:

2023-12-26 12:04 UTC, mehm8128 commented
>acctiveelementが何かわからなかったそこのテストができてない

ってActivityElementのことですかね？これ↓だと思います
![image](https://github.com/traPtitech/traQ_S-UI/assets/83744975/9533ccdb-fba1-4adf-94ba-5aad1bbc5875)

2023-12-28 02:03 UTC, saitenntaisei commented
マージが原因でなんかすべてが吹き飛んでた

2023-12-28 02:37 UTC, saitenntaisei commented
masterを取り込んだ瞬間にすべてが破壊される

2023-12-28 02:39 UTC, saitenntaisei commented
別に上書きも起きてないし分からず

2023-12-28 02:45 UTC, saitenntaisei commented
master マージする前 

https://github.com/traPtitech/traQ_S-UI/assets/22740400/1e64d0fb-3c96-4839-84fc-e975ad6ae948

2024-01-01 05:13 UTC, saitenntaisei commented
:kan:

2024-01-01 05:13 UTC, saitenntaisei commented on src/components/UI/MessagePanel/MessagePanel.vue
:kan:

2024-01-01 05:24 UTC, saitenntaisei commented
三点とか9点部分clickからmousedownにしても使用感ほとんど変わらないはずという考えで書いた

2024-01-01 07:36 UTC, mehm8128 commented
mousedownにするのは個人的にはあんまりやりたくないですね🤔
現時点で思いついてるのは以下の2つ
- ClickOutsideの対象からいい感じにボタンだけ外す
  - ClickOutsideのclose→それぞれのtoggleで再度表示されてしまっている状態なので、toggleが発火するようなボタンを押したときはClickOutsideのcloseが走らないようにすればいいはず
  - 例えばClickOutsideとボタンとポップアップがセットになったコンポーネントを作るとか？
- closeする関数をsetTimeoutの秒数0で囲む
  - `setTimeout 0`とかで調べれば色々出てくると思うけど、toggleした後にcloseするようにできるので、表示された状態ならclose→closeになって動作自体は問題なくなる

2024-01-02 04:39 UTC, saitenntaisei commented
`setTimeout  0`が楽そうだったのでそれで解決

2024-01-02 05:22 UTC, mehm8128 reviewed
importの順序変わって余計な差分出てそうなので直してほしいです(機能の差分が分かりづらくてレビューしづらいので)

2024-01-02 05:54 UTC, saitenntaisei commented
これなんで発生してるのかわからんくて困ってる

2024-01-02 06:00 UTC, mehm8128 commented
保存時に勝手に入れ替わるなら拡張機能のせいか、手元のglobalなprettier or eslintの設定が変に効いちゃってるとかだと思います
保存時に入れ替わらないなら分からないので、とりあえず手動で戻しておいてください

2024-01-02 08:14 UTC, mehm8128 commented on src/components/UI/MessagePanel/MessagePanel.vue
意図してたのは`.icon`の方ではなくて`.container`の`cursor: pointer;`ですね

2024-01-03 01:50 UTC, saitenntaisei commented on src/components/UI/MessagePanel/MessagePanel.vue
普通にミスってた　直した

2024-01-03 01:54 UTC, saitenntaisei commented
@mehm8128  .containerと.iconのやつ直しました

2024-01-03 04:53 UTC, mehm8128 requested changes
よさそうだと思ったのですが、スマホでサイドバーを開いたときに暗くなってる部分をタップしてもサイドバーが閉じなくなってしまってますね:eyes_komatta:(画像を赤く囲った部分)
![image](https://github.com/traPtitech/traQ_S-UI/assets/83744975/42a291d2-b5ed-4b50-8204-3bb843431283)

2024-01-03 05:35 UTC, saitenntaisei commented
それもとからできないが

2024-01-03 05:38 UTC, mehm8128 commented
あれ、ほんとだ
別でissue立てておきます

2024-01-03 05:40 UTC, saitenntaisei commented
re-req投げられば良い感じ?

2024-01-03 05:41 UTC, mehm8128 approved these changes
じゃあ問題なさそうです

2024-01-03 05:42 UTC, merged