テーマ設定のUI改善
traPtitech/traQ_S-UI pull request #4154
Opened 2023-11-17 12:33 UTC by Nattuki

#2203 
設計図通りにテーマ設定のレイアウト・様式変更してみました。

変更前
<img width="1165" alt="スクリーンショット 2023-11-17 21 27 37" src="https://github.com/traPtitech/traQ_S-UI/assets/107347356/0df9bd55-7f74-4987-862d-50abe97994e0">

変更後
<img width="1142" alt="スクリーンショット 2023-11-17 21 27 58" src="https://github.com/traPtitech/traQ_S-UI/assets/107347356/24352bfc-455e-4ff1-868d-7079f22cffb9">

2023-11-17 14:45 UTC, mehm8128 requested changes
PRありがとうございます！
いくつかあるので、対応お願いします

2023-11-17 14:45 UTC, mehm8128 commented on src/views/Settings/ThemeTab.vue
> +  position: relative;
![ask](https://img.shields.io/badge/review-ask-blue.svg)
これってどこかに影響してますか？消してよさそうな気がします

2023-11-17 14:45 UTC, mehm8128 commented on src/views/Settings/ThemeTab.vue
> +  margin-left: 0px;
![imo](https://img.shields.io/badge/review-imo-yellow.svg)
margin-leftは初期値が0なので、0pxならこのCSS自体消しちゃってよさそうです
https://developer.mozilla.org/ja/docs/Web/CSS/margin-left#%E5%85%AC%E5%BC%8F%E5%AE%9A%E7%BE%A9

2023-11-17 14:45 UTC, mehm8128 commented on src/components/Settings/ThemeTab/EditTheme.vue
> +  }
![should](https://img.shields.io/badge/review-should-important.svg)
ここは多分コンポーネント自体を直した方がよくて、デザインチームとの相談にもなると思うので一旦消しておいてほしいです:pray:

2023-11-17 14:45 UTC, mehm8128 commented on src/components/Settings/ThemeTab/EditTheme.vue
> +  margin-top: -46px;
![should](https://img.shields.io/badge/review-should-important.svg)
基本的にmarginに負の数値を使うのは分かりづらくなってしまうので避けたいです

デザイン通りにするなら`position: relative・abosulte`使っていい感じにするか、headingとこのボタンを囲うcontainerに`display: flex`をつけるかになりそうなのですが、ちょっと複雑な実装になってしまいそうなのでデザインから考え直す必要があるかもです
@SSlime-s なんかいい方法あったりしたら教えてほしいです:pray:

2023-11-17 14:45 UTC, mehm8128 commented on src/views/Settings/ThemeTab.vue
> +  display: block;
ラジオボタンとテキストでちょっと上下にずれてしまっている(分かりづらいけど、多分テキストがちょっと下にずれてる)ので、`display: flex`にして`align-items: center`で上下揃えるのがいいと思います
![image](https://github.com/traPtitech/traQ_S-UI/assets/83744975/a270798e-983b-4901-a2e9-a0a816fe21a3)

2023-11-17 14:45 UTC, mehm8128 commented on src/views/Settings/ThemeTab.vue
>  .form {
![should](https://img.shields.io/badge/review-should-important.svg)
Figmaでは`font-weight: bold`になっていて、選択されていない部分の文字の色が変わっているので、対応してほしいです:pray:
と思ったのですがFIgmaでは使う色自体は同じで、透過率を0.5にしてるので`opacity: 0.5`とかにするとよさそうです
![image](https://github.com/traPtitech/traQ_S-UI/assets/83744975/d9eac6a0-870d-4236-b337-ce94b35b0dd9)

2023-11-17 14:45 UTC, mehm8128 commented on src/components/Settings/ThemeTab/EditTheme.vue
![must](https://img.shields.io/badge/review-must-red.svg)
`import/export`ボタン押したら多分モーダルが表示される仕様に変わっていると思うので、そうしてほしいです
モーダルのデザインはページのデザインの左側にあったやつです
https://www.figma.com/file/6Wme6N24y3GN2jD0vqZWZr/traQ-S-UI?type=design&node-id=7896-31272&mode=design&t=dzMKNsZogm4CAo4s-4

2023-11-17 14:56 UTC, SSlime-s commented on src/components/Settings/ThemeTab/EditTheme.vue
> +  margin-top: -46px;
Heading を囲うタグを追加して、Heading と このコンポーネントを flex とかで横並びにするしかない気がする
頼りになれなくて sry :pray:

2023-11-17 15:00 UTC, Nattuki commented on src/views/Settings/ThemeTab.vue
> +  margin-left: 0px;
フォーマット的に統一したい気持ちがあって残しちゃったのです。
把握しました。

2023-11-17 15:00 UTC, Nattuki commented on src/components/Settings/ThemeTab/EditTheme.vue
> +  }
把握しました。

2023-11-17 15:03 UTC, Nattuki commented on src/components/Settings/ThemeTab/EditTheme.vue
> +  margin-top: -46px;
ここの部分の実装に関してどうすればいいのか確かにめちゃめちゃ悩んでいました。
後でやってみます！ありがとうございます！！

2023-11-17 15:07 UTC, Nattuki commented on src/views/Settings/ThemeTab.vue
> +  display: block;
なるほど。わかりました。

2023-11-17 15:08 UTC, Nattuki commented on src/components/Settings/ThemeTab/EditTheme.vue
後で確認します！！

2023-11-17 15:08 UTC, Nattuki commented on src/views/Settings/ThemeTab.vue
>  .form {
わかりました！

2023-11-29 10:42 UTC, mehm8128 requested changes
動きは大体よさそうです！
細かいところ書いたので確認してほしいです:pray:

2023-11-29 10:42 UTC, mehm8128 commented on src/components/UI/FormRadio.vue
> +  }
![should](https://img.shields.io/badge/review-should-important.svg)
`aria-checked`はlabelタグにはつけられないので、指定してる部分消してほしいです:pray:
代わりに、CSSはこんな書き方ができます↓
```suggestion
  &:has(.radio:not(:checked)) {
    opacity: 0.5;
  }
```

2023-11-29 10:42 UTC, mehm8128 commented on src/components/Modal/EditThemeModal/EditThemeModal.vue
> +  <modal-frame title="カスタムテーマ" icon-name="edittheme">
icon-nameに存在しないアイコン名指定しててエラー出てるのですが、コンポーネント自体を直す必要があって僕が直してる途中なので、一旦空文字にしておいてほしいです:pray:
```suggestion
  <modal-frame title="カスタムテーマ" icon-name="">
```
![image](https://github.com/traPtitech/traQ_S-UI/assets/83744975/bd0c4add-054e-43d5-ae05-3beb3e51886a)

2023-11-29 10:42 UTC, mehm8128 commented on src/components/Modal/EditThemeModal/EditThemeModal.vue
> +      } else {
![must](https://img.shields.io/badge/review-must-red.svg)
changeThemeしたあとモーダル閉じたいです

2023-11-29 10:42 UTC, mehm8128 commented on src/views/Settings/ThemeTab.vue
> +  gap: 10px;
![nits](https://img.shields.io/badge/review-nits-lightgray.svg)
gapはなくてもよさそうです

2023-11-29 10:43 UTC, mehm8128 commented
あと、再レビューしてOKな状態になったらここから再レビュー依頼お願いします
![image](https://github.com/traPtitech/traQ_S-UI/assets/83744975/0b86ead3-ce14-44a1-b1da-a72a74b31dae)

2023-12-26 14:32 UTC, mehm8128 reviewed
https://github.com/traPtitech/traQ_S-UI/pull/4154#discussion_r1436471133
ここだけ直してほしいです:pray:
あとはよさそうです

2023-12-26 14:54 UTC, mehm8128 commented on src/components/UI/FormRadio.vue
> +  <label :class="$style.label" :aria-checked="isChecked">
![nits](https://img.shields.io/badge/review-nits-lightgray.svg)
あ、ここ`:aria-checked="isChecked"`消し忘れだと思うので消しておいてほしいです

2024-01-29 06:30 UTC, mehm8128 reviewed
見てたら追加で気づいたので🙏

2024-01-29 06:30 UTC, mehm8128 commented on src/views/Settings/ThemeTab.vue
> +  font-weight: bold;
![should](https://img.shields.io/badge/review-should-important.svg)
```css
display: flex;
align-items: center;
```
は`FormRadio`側で定義してるから多分いらなくて、`font-weight: bold;`は多分全ラジオボタンで共通になるので`FormRadio`側に移動してほしいです🙏

2024-01-29 06:30 UTC, mehm8128 commented on src/views/Settings/ThemeTab.vue
> +  margin-left: 0px;
![nits](https://img.shields.io/badge/review-nits-lightgray.svg)
これ前に消したっけ？復活してそう

2024-05-09 11:22 UTC, mehm8128 approved these changes
よさそうです、ありがとうございました！

2024-05-10 15:13 UTC, merged