設定画面のセッションタブの改修
traPtitech/traQ_S-UI pull request #4155
Opened 2023-11-17 12:50 UTC by SSlime-s

元issue #2203 

![image](https://github.com/traPtitech/traQ_S-UI/assets/62363188/bed0e7e7-497e-4246-ac32-d00deb27fe30)

Figma: https://www.figma.com/file/6Wme6N24y3GN2jD0vqZWZr/traQ-S-UI?type=design&node-id=9741-24242&mode=dev

#### 動作確認
`アクセスを許可しているアプリ` の欄は (:tabun:) 本番環境でないと中身が入った状態を見れない
手元で試す場合は `./dev.config.ts` を `export const DEV_SERVER_PROXY_HOST = 'https://q.trap.jp'` に書き換えて、本番環境を指すようにする

2023-11-17 15:46 UTC, mehm8128 requested changes
ありがとうございます！
いくつか:pray:

2023-11-17 15:46 UTC, mehm8128 commented on src/components/Settings/SessionTab/TokenManager.vue
> +    <ul v-if="tokensWithClientData.length > 0" :class="$style.content">
![imo](https://img.shields.io/badge/review-imo-yellow.svg)
ここってv-elseで`Loading...`とか出さなくて大丈夫ですか？
一応ユーザーモーダルでは`Now loading...`を出してます

2023-11-17 16:26 UTC, SSlime-s commented on src/components/Settings/SessionTab/ViewStates.vue
> +    <p v-else>他端末/ブラウザ/タブで開いているチャンネルはありません。</p>
あ～ 意図せず未読消化されちゃうのを検知するみたいな文脈だったと思うので、他のタブで開いてても未読消化されないなら消しちゃってもいいような気がします
cc: @annin3

2023-11-17 16:28 UTC, SSlime-s commented on src/components/Settings/SessionTab/ViewStates.vue
>      <h3 :class="$style.header">閲覧中チャンネル一覧</h3>
変え忘れてました :pray:
修正しました

2023-11-17 16:30 UTC, SSlime-s commented on src/views/Settings/SessionTab.vue
> +    <h2 :class="$style.visuallyHidden">セッション</h2>
あー ここ section ネストになってるのか
見出しのない `<section>` 使ってるのが :eyes_komatta: だったので、`<section>` やめる形で修正しました :pray:

2023-11-17 16:33 UTC, SSlime-s commented on src/components/Settings/SessionTab/TokenInfo.vue
> +        <a-icon name="close" mdi aria-label="無効化" />
`トークンを無効化` にしてどうせなので、button に title で書くようにしました :pray:

2023-11-17 16:39 UTC, SSlime-s commented on src/components/Settings/SessionTab/TokenInfo.vue
> +        <template v-else>---</template>
まぁ わかる
これって `---` になる条件って スタンプとかで unknown がでるときと条件一緒ですよね？
(ref: https://github.com/traPtitech/traQ_S-UI/blob/SSlime/imp-settings-session-tab/src/components/Settings/SessionTab/TokenManager.vue#L41)
てきとうなアイコンつけるなら unknown に統一してもいいのかな とちょっと思いました

存在しないなにかに使ってるアイコンとかは現状なさそう？

cc: @annin3

2023-11-17 16:41 UTC, SSlime-s commented on src/components/Settings/SessionTab/TokenManager.vue
> +    <ul v-if="tokensWithClientData.length > 0" :class="$style.content">
読み込み結構一瞬で、チカチカするかなと思って特に何もいれないことにしてました
まぁ正味入れてもいいです

cc: @annin3

2023-11-18 03:48 UTC, mehm8128 commented on src/components/Settings/SessionTab/ViewStates.vue
> +    <p v-else>他端末/ブラウザ/タブで開いているチャンネルはありません。</p>
他のタブで開いてても未読消化されない＆通知もくるようになってるので、それなら消しちゃってよさそうです

2023-11-18 03:53 UTC, mehm8128 commented on src/components/Settings/SessionTab/TokenInfo.vue
> +        <template v-else>---</template>
なるほど、確かにunknownでよさそうです
今のところそういう感じのアイコンはない気がします

2023-11-18 04:01 UTC, mehm8128 reviewed
すみません1つ追加で:pray:

2023-11-18 05:19 UTC, SSlime-s commented on src/components/Settings/SessionTab/PasswordChange.vue
> +        :href="changeLink"
:crab: 変更しました

2023-11-19 13:15 UTC, annin3 commented on src/components/Settings/SessionTab/ViewStates.vue
> +    <p v-else>他端末/ブラウザ/タブで開いているチャンネルはありません。</p>
大丈夫だと思います！消す方向でお願いします

2023-11-19 13:22 UTC, annin3 commented on src/components/Settings/SessionTab/TokenInfo.vue
> +        <template v-else>---</template>
自分もunknownで良いと思います
存在しない何かに使ってるアイコンはないはずだけど用意したいっすね(すぐすぐは無理なので別issueとして。。。)
一旦アイコンなしで`unknown`って名前だけ置いといてもらえると:pray:

2023-11-19 13:25 UTC, annin3 commented on src/components/Settings/SessionTab/TokenManager.vue
> +    <ul v-if="tokensWithClientData.length > 0" :class="$style.content">
本当に一瞬なら必要ないとは思いますが、ユーザーモーダルに出してるなら入れても良いか。。。
手間かからないならとりあえず入れてもらっていいですか？少しでもめんどくさかったらなくて大丈夫です。

2023-11-19 13:26 UTC, SSlime-s commented on src/components/Settings/SessionTab/TokenManager.vue
> +    <ul v-if="tokensWithClientData.length > 0" :class="$style.content">
入れるのは一瞬なので大丈夫です 👌

2024-01-22 12:59 UTC, mehm8128 commented on src/components/Settings/SessionTab/TokenManager.vue
> +    <ul v-if="tokensWithClientData.length > 0" :class="$style.content">
別件でbot-consoleをローカルでいじってたら開発環境でもセッション表示できたのですが、数が少ないときに表示がおかしくなっていたので直してほしいです🙏(別のブランチで見ても表示崩れてたので、元からっぽいです)
`li`に高さ設定するとかがいいんですかね🤔
![image](https://github.com/traPtitech/traQ_S-UI/assets/83744975/94aa7520-2fb6-4005-8573-82af25c775ea)

参考: 変更前も崩れている様子
![image](https://github.com/traPtitech/traQ_S-UI/assets/83744975/485a49fa-ab17-419d-91a3-b93dd0e793e8)

2024-01-22 13:11 UTC, SSlime-s commented on src/components/Settings/SessionTab/TokenManager.vue
> +    <ul v-if="tokensWithClientData.length > 0" :class="$style.content">
`grid-template-rows: max-content` とかつけたら治りそうな感じがするというメモだけ残して修正はこんどします
感謝です :pray:

2024-02-02 17:24 UTC, SSlime-s commented on src/components/Settings/SessionTab/TokenManager.vue
> +    <ul v-if="tokensWithClientData.length > 0" :class="$style.content">
`grid-auto-rows` でした
治しました :pray:

2024-02-02 17:24 UTC, SSlime-s commented on src/components/Settings/SessionTab/TokenInfo.vue
> +        <template v-else>---</template>
unknown のみ置くように変更しました :pray:

2024-02-02 17:24 UTC, SSlime-s commented on src/components/Settings/SessionTab/TokenManager.vue
> +    <ul v-if="tokensWithClientData.length > 0" :class="$style.content">
入れました :pray:

2024-02-02 17:24 UTC, SSlime-s commented on src/components/Settings/SessionTab/ViewStates.vue
> +    <p v-else>他端末/ブラウザ/タブで開いているチャンネルはありません。</p>
消しました :pray:

2024-02-03 02:39 UTC, mehm8128 approved these changes
よさそうです:kansya_kansya:

2024-02-05 13:08 UTC, mehm8128 commented
マージ権限ないの忘れてたのでマージします

2024-02-05 13:08 UTC, merged