引用の日付をメッセージのものと合わせるように
traPtitech/traQ_S-UI pull request #4385
Opened 2024-10-23 16:25 UTC by nokhnaton

fix: #4368

2024-10-26 23:30 UTC, ras0q requested changes

2024-10-26 23:30 UTC, ras0q commented on src/lib/basic/date.ts
> +  return getDateRepresentation(createdAt)
この変更で元の関数は使われなくなるので消して良さそうです

2024-10-26 23:30 UTC, ras0q commented on src/lib/basic/date.ts
> +export const getDateRepresentation = (date: string) => {
[IMO] 引数をgetTimeRepresentationWithoutSameDateみたいな形にしてfromのデフォルトをnew Date()にすると型の恩恵を受けられテストもしやすくて使いやすいと思いました

2024-10-26 23:30 UTC, ras0q commented on src/lib/basic/date.ts
> +}
[IMO] date.ts側でcreatedAtとupdatedAtのロジックを持つ必要はなくて使う側で適切にupdatedAtのみを渡すべきだと思うので、このタイミングか別PRでついでに直してもらえると助かります🙏
同じ理由でgetCreatedDateもいらないと思う

2024-10-27 04:17 UTC, nokhnaton commented on src/lib/basic/date.ts
> +}
getDisplayDateに日付のパース等も含めたロジックを持たせてgetCreatedDateと統合することにします:saluting_face:

2024-10-27 23:25 UTC, ras0q commented on src/lib/basic/date.ts
>  }
現状はcreatedAtとupdatedAtのうち片方しか使われない（制御結合）形になっているんですが、↓のようにどちらを使うかは外側で決めて変換には必要な日付のみを渡す（データ結合）方がモジュール結合度が低くて運用しやすいんじゃないかなって思います
つまりはgetDisplayDateは消してgetDateRepresentationを広く使いたいねって話です（関数名はgetDisplayDateでもいいんですが）

https://github.com/traPtitech/traQ_S-UI/blob/c8d676156d7327373804594fe7ebb09d1ddc048c/src/components/Main/CommandPalette/SearchResultMessageElement.vue#L85-L96

2024-10-27 23:26 UTC, ras0q commented on src/lib/basic/date.ts
> +  const displayDate = date
```suggestion
export const getDateRepresentation = (displayDate: Readonly<Date>) => {
```

2024-10-28 04:46 UTC, nokhnaton commented on src/lib/basic/date.ts
>  }
あー、確かにこんな感じの使い方がありえるならgetDateRepresentationを広く使う方が良さそうですね

2024-10-28 12:50 UTC, ras0q approved these changes
よさそうです！

2024-10-28 12:51 UTC, merged